[build]
  base = "web/"
  command = "npm run build"
  publish = "public/"

[[redirects]]
  from = "/eon-multi-surface"
  to = "/products/eon-multi-surface-disinfectant"
  status = 301

[[redirects]]
  from = "/q1"
  to = "/q2"
  status = 301
  